# Template .toml file for NAVPERS 1610/2 (aka FITREP).
# This file can be converted into a NAVPERS 1610/2 PDF via NAVFITX.
# Link: https://github.com/tristan-white/navfitx

[report]
# Date service member reported to command.
# Format: YYYY-MM-DD
date_reported = "2022-09-09"

# If this is a wholly Not Observed report, change to true.
not_observed_report = false

counselor_name = "DOE, J"
date_counseled = "2024-08-14"

[report.type]
regular = false
concurrent = false
ops_cdr = false

[report.occasion]
# Change to true each reporting occasion that applies.
# See BUPERSINST 1610.10H chapter 3 for reporting occasions.
periodic = false
detachment_of_individual = false
detachment_of_reporting_senior = false
special = false

[report.period]
from = "2024-05-27"
to = "2025-02-28"

[member]
# Enter the member's last name, first name, middle initial, and suffix (if any)
# separated by spaces. Place a comma after the last name. Omit spaces and punctuation within a
# name (e.g., Denney, John A; STJohn, Melvin J II; Walters, J Arthur; Obrien, Mary S; Martin,
# Paul T JR; SmithJones, Ann.). The full middle name is acceptable but not required. NMN may
# be used if member does not have a middle name.
name = "DOE, JOHN A"

# Enter the grade or rate the Service member is actually wearing on the ending date of the report.
# Enlisted: Use standard rate abbreviations (e.g., SA, ADAN, CS2, BM1, LNC, EMCS, PSCM, etc.).
# Officers: Use standard grade abbreviations (e.g., CAPT, CDR, LCDR, LT, LTJG, ENS, CWO5, CWO4, CWO3, CWO2, WO1 etc.).
# Note 1: This field is used for summary group comparison.
# Note 2: The CHIEFEVAL identifies this block as “Rating.” Standard abbreviations remain as the required information
# and the rate/rating the member is currently wearing should be entered here.
grade_or_rate = "LTJG"

# Enter officer designator or enlisted warfare qualification designation.
# Enlisted: Enter up to two enlisted warfare/qualification designators. If two designators are
# entered, separate with a slash. Do not leave spaces (e.g., AW, AW/PJ, SS/DV etc.) (if none,
# leave blank).
# Officers: Enter the four-digit officer designator as of the ending date of report. Do not use an
# alpha character for a numerical character.
designator = "1840"

# Format: "XXX-XX-XXX"
ssn = "000-00-0000"

uic = ""

activity = ""

promotion_status = ""

# Can be either "P", "B", "F", "M", "W", or "N"
physical_readiness = ""

billet_subcategory = ""

[report.summary_group]
ACT = false
FTS = false
INACT = false
AT_or_ACDU_or_ADSW = false

[reporting_senior]
name = ""
grade = ""
designator = ""
title = ""
uic = 12345
# Format: "XXX-XX-XXX"
ssn = ""

[performance_traits]
# Set each category 1 through 5, or 0 for Not Observed.
professional_expertise = 0
climate = 0
bearing_and_character = 0
teamwork = 0
mission = 0

[career_recommendations]
# Enter one or two career recommendations. The second recommendation is not required. 
# Each entry may have a maximum of 20 characters and spaces. If necessary, use two lines for the entry.
# Do not leave blank. If no recommendation is appropriate, enter “NA” or “NONE” in the first block.
recommendation_1 = ""
recommendation_2 = ""

[comments_on_performance]
# Max of 18 lines.
# Max of 91 characters per line (not including newline characters).
###########################################################################################
comments_on_performance = """
"""
