site_name: NAVFITX
site_url: https://navfitx.com
repo_url: https://github.com/tristan-white/navfitx
theme:
  name: material
  icon:
    logo: material/clipboard-edit
  palette: 
    scheme: slate
    primary: indigo
  features:
    # - navigation.tabs
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
plugins:
  # - termynal:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
nav:
  - Home: index.md
  - Docs: docs.md
  - Why: why.md
  # - FAQs: faqs.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tristan-white/navftix
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/navfitx/

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format