blank_issues_enabled: false
contact_links:
  - name: Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/tristan-white/navfitx/discussions/categories/questions
  - name: Feature Request
    about: To suggest an idea or ask about a feature, please start with a question saying what you would like to achieve. There might be a way to do it already.
    url: https://github.com/tristan-white/navfitx/discussions/categories/questions
  - name: Show and tell
    about: Has NAVFITX helped you, your shipmates, or your command? Share a NAVFITX success story.
    url: https://github.com/tristan-white/navfitx/discussions/categories/show-and-tell
